
all:
	$(MAKE) -C util
	$(MAKE) -C ops
	$(MAKE) -C slo
	$(MAKE) -C ir
	$(MAKE) -C xf
	$(MAKE) -C cg

tests:
	$(MAKE) tests -C util
	$(MAKE) tests -C ops
	$(MAKE) tests -C slo
	$(MAKE) tests -C ir
	$(MAKE) tests -C xf
	$(MAKE) tests -C cg

clean:
	$(MAKE) clean -C util
	$(MAKE) clean -C ops
	$(MAKE) clean -C slo
	$(MAKE) clean -C ir
	$(MAKE) clean -C xf
	$(MAKE) clean -C cg
