TOP_DIR = ../../..
include $(TOP_DIR)/build/Makefile_common

SRCS = \
	IRArrayType.cpp \
	IRBasicInst.cpp \
	IRBlock.cpp \
	IRCatchStmt.cpp \
	IRConst.cpp \
	IRControlStmt.cpp \
	IRDetail.cpp \
	IRForLoop.cpp \
	IRGatherLoop.cpp \
	IRGlobalVar.cpp \
	IRIfStmt.cpp \
	IRIlluminanceLoop.cpp \
	IRIlluminateStmt.cpp \
	IRInst.cpp \
	IRLocalVar.cpp \
	IRNumArrayConst.cpp \
	IRNumConst.cpp \
	IRPluginCall.cpp \
	IRPos.cpp \
	IRSeq.cpp \
	IRShader.cpp \
	IRShaderParam.cpp \
	IRSpecialForm.cpp \
	IRStmt.cpp \
	IRStringArrayConst.cpp \
	IRStringConst.cpp \
	IRStructType.cpp \
	IRType.cpp \
	IRTypes.cpp \
	IRUnknownInst.cpp \
	IRValue.cpp \
	IRVar.cpp \
	IRVarSet.cpp \
	$(NULL)

SRC_DIR = src/lib/ir
LIB_NAME = libir.a

include $(TOP_DIR)/build/Makefile_lib
