TOP_DIR = ../../../..
include $(TOP_DIR)/build/Makefile_common

TEST_SRCS = \
	TestOpVec3.cpp \
	TestOpVec4.cpp \
	TestOpMatrix3.cpp \
	TestOpMatrix4.cpp \
	$(NULL)

SRC_DIR = src/lib/ops/tests
LIBS = libops.a

include $(TOP_DIR)/build/Makefile_tests
