TOP_DIR = ../../../..
include $(TOP_DIR)/build/Makefile_common

TEST_SRCS = \
	TestUtDelete.cpp \
	TestUtHashMap.cpp \
	TestUtLog.cpp \
	TestUtTimer.cpp \
	TestUtToken.cpp \
	TestUtVector.cpp \
	$(NULL)

OTHER_SRCS = \
	$(NULL)

SRC_DIR = src/lib/util/tests
LIBS = libutil.a

include $(TOP_DIR)/build/Makefile_tests
