TOP_DIR = ../../..
include $(TOP_DIR)/build/Makefile_common

SRCS = \
	UtCast.cpp \
	UtDelete.cpp \
	UtLog.cpp \
	$(NULL)

SRC_DIR = src/lib/util
LIB_NAME = libutil.a

include $(TOP_DIR)/build/Makefile_lib
