TOP_DIR = ../../..
include $(TOP_DIR)/build/Makefile_common

SRCS = \
	SloEnums.cpp \
	SloFile.cpp \
	SloHeader.cpp \
	SloInfo.cpp \
	SloInputFile.cpp \
	SloInst.cpp \
	SloOutputFile.cpp \
	SloShader.cpp \
	SloSymbol.cpp \
	$(NULL)

SRC_DIR = src/lib/slo
LIB_NAME = libslo.a

include $(TOP_DIR)/build/Makefile_lib
